### ISSUE TITLE
Anotações

### ISSUE THREAD

**Issue by cjlcarvalho** [cjlcarvalho/ulcer-image-segmentation#1]
Construir anotações em XML das images que faltam.

Executar annotate.py com os novos arquivos XML.

**Comment by cjlcarvalho** [comment]
@DaniloD30 anotações das úlceras de perna completas. Agora só falta as de pressão.

**Comment by DaniloD30** [comment]
Tranquilo, hoje a noite, darei uma adiantada nas anotações.

Em ter, 4 de set de 2018 às 23:52, Caio Jordão Carvalho <
notifications@github.com> escreveu:

**Comment by DaniloD30** [comment]
Iniciei as anotações, das úlceras de pressão.

Em qua, 5 de set de 2018 às 14:41, Danilo Oliveira Dias <
danilolive30@hotmail.com> escreveu:
